### ISSUE TITLE
Put documentation somewhere

### ISSUE THREAD

**Issue by sils1297** [python-babel/django-babel#12]
would be nice if you'd put the documentation somewhere, either ask `mitsuhiko` on IRC if you can have a django-babel.pocoo.org documentation or use readthedocs.org, would be my recommendation.

**Comment by graingert** [comment]
I plan to get it building on django-babel.readthedocs.org

**Comment by sils1297** [comment]
Cool, then we can track that here :)

2015-09-21 22:50 GMT+02:00 Thomas Grainger <notifications@github.com>:
