### ISSUE TITLE
Docs: module index link is broken

### ISSUE THREAD

**Issue by sils1297** [python-babel/django-babel#14]

**Comment by graingert** [comment]
That's because there aren’t any modules yet :(

**Comment by sils1297** [comment]
Well then the link shouldn't be there (yet), right?

**Comment by sils1297** [comment]
Confusing users.

**Comment by sils1297** [comment]
Still: maze found. https://django-babel.readthedocs.org/en/latest/py-modindex.html

**Comment by willkg** [comment]
I don't understand what this issue is about. The link in https://github.com/python-babel/django-babel/issues/14#issuecomment-142272818 works fine for me. Further, the modules link on the docs also works.

@sils1297 Is this still an issue?

**Comment by sils1297** [comment]
Seems solved
