### ISSUE TITLE
support "trimmed" in blocktrans

### ISSUE THREAD

**Issue by willkg** [python-babel/django-babel#20]
Django 1.7 added a "trimmed" option for blocktrans tags. When that's enabled, then it strips whitespace from the beginning and end of strings as well as collapses consecutive whitespace characters in the string.

I'm pretty sure django-babel's extractor doesn't support that.

Is that correct? If so, can support for that be added?

**Comment by graingert** [comment]
we have no special checks for trimmed, I'm happy to merge a PR with a test case and fix for this though :)

**Comment by willkg** [comment]
Awesome! I'll work on it with all due haste. Thank you!

**Comment by mrunge** [comment]
This issue should be closed with above patch.
