### ISSUE TITLE
New pypi release

### ISSUE THREAD

**Issue by richardasaurus** [python-babel/django-babel#29]
Can you make a new pypi release with the latest changes? (Django 1.9 i'm after)

**Comment by Itxaka** [comment]
+1

**Comment by mrunge** [comment]
OpenStack Horizon is currently blocked on missing Django-1.9 support in django-babel. It would be great, if you could tag a release and upload it to pypi. 

Thank you.

**Comment by graingert** [comment]
I don't have a great deal of time to maintain this, @mrunge would you like to take this over as part of Open Stack?

**Comment by mrunge** [comment]
@graingert yes, I'm definitely in with helping out here.

**Comment by graingert** [comment]
Sweet, what's your username on PyPI?

**Comment by mrunge** [comment]
good question, I might not be registered yet. I'll figure out. 
Otherwise, we still need a tag pushed here, for the new release.

**Comment by mrunge** [comment]
@graingert 
pypi username is mrunge

**Comment by graingert** [comment]
@mrunge you can now upload with "python setup.py sdist bdist_wheel register upload"

**Comment by graingert** [comment]
@python-babel/babel-admins can you add @mrunge to @python-babel/django-babel-developers please?

**Comment by sils1297** [comment]
Invitation to @mrunge is out. I'm adding myself to babel-admins so I get notified next time.

**Comment by mrunge** [comment]
@graingert , @sils1297 
awesome, that worked already, thanks a lot!

**Comment by sils1297** [comment]
@graingert GitHub permissions are quite confusing especially since they tried to improve it. They somehow managed to make it more complicated but still not more useful than before :P Apparently I can't give you access to invite people to the team, you're already team maintainer fwiw...

**Comment by mrunge** [comment]
oops. I just added a tag here, and uploaded a version 0.5.0 to pypi. 

For next time, I need to learn to add a changelog etc. first here, then finally upload to pypi.

**Comment by graingert** [comment]
@mrunge zest.releaser is a pretty cool tool for automating releases

**Comment by mrunge** [comment]
thanks for the hint. I will definitely have a look at it. 

Every project handles this differently :-/

**Comment by graingert** [comment]
@mrunge well you're release manager now, so you get to decide :p
