### ISSUE TITLE
Django 1.10 support

### ISSUE THREAD

**Issue by sassanh** [python-babel/django-babel#32]
It doesn't seem to work with django 1.10, I guess just upgrading the checker to accept 1.10 would be enough:

```
pkg_resources.VersionConflict: (Django 1.10 (/x/y/z/lib/python3.5/site-packages), Requirement.parse('django<1.10,>=1.4'))
```

**Comment by sassanh** [comment]
Any updates on this issue? I see some commits referencing this issue, but latest version of django-babel still conflicts with django 1.10 (`pip install --upgrade django-babel` tries to downgrade django to 1.9)

**Comment by mrunge** [comment]
I'm sorry about this, my focus shifted completely away

**Comment by graingert** [comment]
Also I was trying to leave comments here, but they got caught in github's new review queue tool
