### ISSUE TITLE
Release for compatibility support

### ISSUE THREAD

**Issue by noirbizarre** [python-babel/django-babel#35]
Hi !

Django 1.10 support has been added in #33 and is merged but not yet released.

Is it possible to release this to be able to use it with Django 1.10 ?

Thansk by advance !

**Comment by orf** [comment]
+1, this is quite an important fix!

**Comment by graingert** [comment]
I currently don't have time to manage releases of django-babel: I've added @akx @sils and @mitsuhiko to django-babel contributors

**Comment by orf** [comment]
@akx @sils or @mitsuhiko are you able to push a new release?

**Comment by sils** [comment]
no, not me sorry. Too much other stuff going on :/

**Comment by akx** [comment]
Hey,

sorry for the delay, but good news :tada: I just released 0.6.0!
(Here's hoping I did it right – no maintainer instructions in sight...)

* GitHub release here: https://github.com/python-babel/django-babel/releases/tag/0.6.0
* On PyPI as usual, too: https://pypi.python.org/pypi/django-babel
