### ISSUE TITLE
New release on PyPI for Django 1.11

### ISSUE THREAD

**Issue by robcresswell** [python-babel/django-babel#38]
Hey! I saw that django-babel has Django 1.11 support on master. Could we get a release on PyPI for downstream consumers?

Thanks

**Comment by benselme** [comment]
@akx That's an important one ! Do you have the rights to make a release on PyPI ?

**Comment by robcresswell** [comment]
It's relatively critical for us, since OpenStack Horizon relies on it, and requirements freeze is next week. If I can do anything to help the process along, please let me know.

**Comment by akx** [comment]
@benselme I do indeed!

@robcresswell I'll do this tomorrow morning! :)

**Comment by robcresswell** [comment]
Fantastic. Thanks so much!

**Comment by akx** [comment]
@robcresswell: 0.6.1 released 😸  https://pypi.org/project/django-babel/

**Comment by robcresswell** [comment]
@akx Great, thanks again
